hostname ce1
!
interface lo
 ip address 10.1.0.1/32
exit
!
interface eth1
 ip address 192.168.11.1/30
exit
!
interface eth2
 ip address 192.168.12.1/30
exit
!
ip prefix-list PL-LOOPBACK seq 5 permit 10.1.0.1/32
!
route-map RM-CONNECTED permit 10
 match ip address prefix-list PL-LOOPBACK
exit
!
router bgp 65001
 bgp router-id 10.1.0.1
 no bgp ebgp-requires-policy
 neighbor 192.168.11.2 remote-as 65000
 neighbor 192.168.12.2 remote-as 65000
 !
 address-family ipv4 unicast
  neighbor 192.168.11.2 activate
  neighbor 192.168.12.2 activate
  redistribute connected route-map RM-CONNECTED
  maximum-paths 2
 exit-address-family
exit
