frr version 10.7.1_git
frr defaults traditional
hostname ctrl
service integrated-vtysh-config
!
interface eth1
 ipv6 address fc00:0:d::2/64
exit
!
interface eth2
 ipv6 address fc00:0:e::2/64
exit
!
router bgp 65000
 bgp router-id 10.255.0.100
 no bgp default ipv4-unicast
 neighbor fc00:0:d::1 remote-as 65000
 neighbor fc00:0:d::1 description p1
 neighbor fc00:0:e::1 remote-as 65000
 neighbor fc00:0:e::1 description p3
 !
 address-family ipv4 vpn
  neighbor fc00:0:d::1 activate
  neighbor fc00:0:e::1 activate
 exit-address-family
 !
 address-family link-state link-state
  neighbor fc00:0:d::1 activate
  neighbor fc00:0:e::1 activate
 exit-address-family
exit
!
end
