hostname r2
!
interface lo
 ipv6 address fc00::2/128
 ipv6 router isis 1
exit
!
interface eth1
 ipv6 address fc00:12::2/64
 ipv6 router isis 1
 isis network point-to-point
exit
!
interface eth2
 ipv6 address fc00:23::2/64
 ipv6 router isis 1
 isis network point-to-point
exit
!
router isis 1
 is-type level-1
 net 49.0000.0000.0000.0002.00
 topology ipv6-unicast
exit
