hostname ce2
!
interface eth1
 ip address 192.168.23.1/30
exit
!
interface eth2
 ip address 192.168.24.1/30
exit
!
interface eth3
 ip address 10.2.0.1/24
exit
!
ip prefix-list PL-HOSTS seq 5 permit 10.2.0.0/24
!
route-map RM-CONNECTED permit 10
 match ip address prefix-list PL-HOSTS
exit
!
router bgp 65002
 bgp router-id 10.2.0.1
 no bgp ebgp-requires-policy
 neighbor 192.168.23.2 remote-as 65000
 neighbor 192.168.24.2 remote-as 65000
 !
 address-family ipv4 unicast
  neighbor 192.168.23.2 activate
  neighbor 192.168.24.2 activate
  redistribute connected route-map RM-CONNECTED
  maximum-paths 2
 exit-address-family
exit
